// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetAccountByAlpacaID = `-- name: GetAccountByAlpacaID :one
SELECT id, name, account_number, alpaca_id, status, crypto_status, currency, buying_power, regt_buying_power, daytrading_buying_power, effective_buying_power, non_marginable_buying_power, bod_dtbp, cash, accrued_fees, portfolio_value, pattern_day_trader, trading_blocked, transfers_blocked, account_blocked, shorting_enabled, trade_suspended_by_user, multiplier, equity, last_equity, long_market_value, short_market_value, position_market_value, initial_margin, maintenance_margin, last_maintenance_margin, sma, daytrade_count, crypto_tier, alpaca_created_at, created_at, created_by, updated_at, updated_by FROM app.account WHERE alpaca_id = $1
`

func (q *Queries) GetAccountByAlpacaID(ctx context.Context, alpacaID *string) (AppAccount, error) {
	row := q.db.QueryRow(ctx, GetAccountByAlpacaID, alpacaID)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountNumber,
		&i.AlpacaID,
		&i.Status,
		&i.CryptoStatus,
		&i.Currency,
		&i.BuyingPower,
		&i.RegtBuyingPower,
		&i.DaytradingBuyingPower,
		&i.EffectiveBuyingPower,
		&i.NonMarginableBuyingPower,
		&i.BodDtbp,
		&i.Cash,
		&i.AccruedFees,
		&i.PortfolioValue,
		&i.PatternDayTrader,
		&i.TradingBlocked,
		&i.TransfersBlocked,
		&i.AccountBlocked,
		&i.ShortingEnabled,
		&i.TradeSuspendedByUser,
		&i.Multiplier,
		&i.Equity,
		&i.LastEquity,
		&i.LongMarketValue,
		&i.ShortMarketValue,
		&i.PositionMarketValue,
		&i.InitialMargin,
		&i.MaintenanceMargin,
		&i.LastMaintenanceMargin,
		&i.Sma,
		&i.DaytradeCount,
		&i.CryptoTier,
		&i.AlpacaCreatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetAccountByID = `-- name: GetAccountByID :one
SELECT id, name, account_number, alpaca_id, status, crypto_status, currency, buying_power, regt_buying_power, daytrading_buying_power, effective_buying_power, non_marginable_buying_power, bod_dtbp, cash, accrued_fees, portfolio_value, pattern_day_trader, trading_blocked, transfers_blocked, account_blocked, shorting_enabled, trade_suspended_by_user, multiplier, equity, last_equity, long_market_value, short_market_value, position_market_value, initial_margin, maintenance_margin, last_maintenance_margin, sma, daytrade_count, crypto_tier, alpaca_created_at, created_at, created_by, updated_at, updated_by FROM app.account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (AppAccount, error) {
	row := q.db.QueryRow(ctx, GetAccountByID, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountNumber,
		&i.AlpacaID,
		&i.Status,
		&i.CryptoStatus,
		&i.Currency,
		&i.BuyingPower,
		&i.RegtBuyingPower,
		&i.DaytradingBuyingPower,
		&i.EffectiveBuyingPower,
		&i.NonMarginableBuyingPower,
		&i.BodDtbp,
		&i.Cash,
		&i.AccruedFees,
		&i.PortfolioValue,
		&i.PatternDayTrader,
		&i.TradingBlocked,
		&i.TransfersBlocked,
		&i.AccountBlocked,
		&i.ShortingEnabled,
		&i.TradeSuspendedByUser,
		&i.Multiplier,
		&i.Equity,
		&i.LastEquity,
		&i.LongMarketValue,
		&i.ShortMarketValue,
		&i.PositionMarketValue,
		&i.InitialMargin,
		&i.MaintenanceMargin,
		&i.LastMaintenanceMargin,
		&i.Sma,
		&i.DaytradeCount,
		&i.CryptoTier,
		&i.AlpacaCreatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetAccountByNumber = `-- name: GetAccountByNumber :one
SELECT id, name, account_number, alpaca_id, status, crypto_status, currency, buying_power, regt_buying_power, daytrading_buying_power, effective_buying_power, non_marginable_buying_power, bod_dtbp, cash, accrued_fees, portfolio_value, pattern_day_trader, trading_blocked, transfers_blocked, account_blocked, shorting_enabled, trade_suspended_by_user, multiplier, equity, last_equity, long_market_value, short_market_value, position_market_value, initial_margin, maintenance_margin, last_maintenance_margin, sma, daytrade_count, crypto_tier, alpaca_created_at, created_at, created_by, updated_at, updated_by FROM app.account WHERE account_number = $1
`

func (q *Queries) GetAccountByNumber(ctx context.Context, accountNumber *string) (AppAccount, error) {
	row := q.db.QueryRow(ctx, GetAccountByNumber, accountNumber)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountNumber,
		&i.AlpacaID,
		&i.Status,
		&i.CryptoStatus,
		&i.Currency,
		&i.BuyingPower,
		&i.RegtBuyingPower,
		&i.DaytradingBuyingPower,
		&i.EffectiveBuyingPower,
		&i.NonMarginableBuyingPower,
		&i.BodDtbp,
		&i.Cash,
		&i.AccruedFees,
		&i.PortfolioValue,
		&i.PatternDayTrader,
		&i.TradingBlocked,
		&i.TransfersBlocked,
		&i.AccountBlocked,
		&i.ShortingEnabled,
		&i.TradeSuspendedByUser,
		&i.Multiplier,
		&i.Equity,
		&i.LastEquity,
		&i.LongMarketValue,
		&i.ShortMarketValue,
		&i.PositionMarketValue,
		&i.InitialMargin,
		&i.MaintenanceMargin,
		&i.LastMaintenanceMargin,
		&i.Sma,
		&i.DaytradeCount,
		&i.CryptoTier,
		&i.AlpacaCreatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListAccounts = `-- name: ListAccounts :many
SELECT id, name, account_number, alpaca_id, status, crypto_status, currency, buying_power, regt_buying_power, daytrading_buying_power, effective_buying_power, non_marginable_buying_power, bod_dtbp, cash, accrued_fees, portfolio_value, pattern_day_trader, trading_blocked, transfers_blocked, account_blocked, shorting_enabled, trade_suspended_by_user, multiplier, equity, last_equity, long_market_value, short_market_value, position_market_value, initial_margin, maintenance_margin, last_maintenance_margin, sma, daytrade_count, crypto_tier, alpaca_created_at, created_at, created_by, updated_at, updated_by FROM app.account ORDER BY id DESC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]AppAccount, error) {
	rows, err := q.db.Query(ctx, ListAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAccount{}
	for rows.Next() {
		var i AppAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccountNumber,
			&i.AlpacaID,
			&i.Status,
			&i.CryptoStatus,
			&i.Currency,
			&i.BuyingPower,
			&i.RegtBuyingPower,
			&i.DaytradingBuyingPower,
			&i.EffectiveBuyingPower,
			&i.NonMarginableBuyingPower,
			&i.BodDtbp,
			&i.Cash,
			&i.AccruedFees,
			&i.PortfolioValue,
			&i.PatternDayTrader,
			&i.TradingBlocked,
			&i.TransfersBlocked,
			&i.AccountBlocked,
			&i.ShortingEnabled,
			&i.TradeSuspendedByUser,
			&i.Multiplier,
			&i.Equity,
			&i.LastEquity,
			&i.LongMarketValue,
			&i.ShortMarketValue,
			&i.PositionMarketValue,
			&i.InitialMargin,
			&i.MaintenanceMargin,
			&i.LastMaintenanceMargin,
			&i.Sma,
			&i.DaytradeCount,
			&i.CryptoTier,
			&i.AlpacaCreatedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertAccount = `-- name: UpsertAccount :one
INSERT INTO app.account (
    name, account_number, alpaca_id, status, crypto_status, currency,
    buying_power, regt_buying_power, daytrading_buying_power, effective_buying_power,
    non_marginable_buying_power, bod_dtbp, cash, accrued_fees, portfolio_value,
    pattern_day_trader, trading_blocked, transfers_blocked, account_blocked,
    shorting_enabled, trade_suspended_by_user, multiplier, equity, last_equity,
    long_market_value, short_market_value, position_market_value, initial_margin,
    maintenance_margin, last_maintenance_margin, sma, daytrade_count, crypto_tier,
    alpaca_created_at, created_at, created_by, updated_at, updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    NOW(),
    'system',
    NOW(),
    'system'
)
ON CONFLICT (account_number) DO UPDATE SET
    name = EXCLUDED.name,
    account_number = EXCLUDED.account_number,
    status = EXCLUDED.status,
    crypto_status = EXCLUDED.crypto_status,
    currency = EXCLUDED.currency,
    buying_power = EXCLUDED.buying_power,
    regt_buying_power = EXCLUDED.regt_buying_power,
    daytrading_buying_power = EXCLUDED.daytrading_buying_power,
    effective_buying_power = EXCLUDED.effective_buying_power,
    non_marginable_buying_power = EXCLUDED.non_marginable_buying_power,
    bod_dtbp = EXCLUDED.bod_dtbp,
    cash = EXCLUDED.cash,
    accrued_fees = EXCLUDED.accrued_fees,
    portfolio_value = EXCLUDED.portfolio_value,
    pattern_day_trader = EXCLUDED.pattern_day_trader,
    trading_blocked = EXCLUDED.trading_blocked,
    transfers_blocked = EXCLUDED.transfers_blocked,
    account_blocked = EXCLUDED.account_blocked,
    shorting_enabled = EXCLUDED.shorting_enabled,
    trade_suspended_by_user = EXCLUDED.trade_suspended_by_user,
    multiplier = EXCLUDED.multiplier,
    equity = EXCLUDED.equity,
    last_equity = EXCLUDED.last_equity,
    long_market_value = EXCLUDED.long_market_value,
    short_market_value = EXCLUDED.short_market_value,
    position_market_value = EXCLUDED.position_market_value,
    initial_margin = EXCLUDED.initial_margin,
    maintenance_margin = EXCLUDED.maintenance_margin,
    last_maintenance_margin = EXCLUDED.last_maintenance_margin,
    sma = EXCLUDED.sma,
    daytrade_count = EXCLUDED.daytrade_count,
    crypto_tier = EXCLUDED.crypto_tier,
    alpaca_created_at = EXCLUDED.alpaca_created_at,
    updated_at = NOW(),
    updated_by = 'system'
RETURNING id, name, account_number, alpaca_id, status, crypto_status, currency, buying_power, regt_buying_power, daytrading_buying_power, effective_buying_power, non_marginable_buying_power, bod_dtbp, cash, accrued_fees, portfolio_value, pattern_day_trader, trading_blocked, transfers_blocked, account_blocked, shorting_enabled, trade_suspended_by_user, multiplier, equity, last_equity, long_market_value, short_market_value, position_market_value, initial_margin, maintenance_margin, last_maintenance_margin, sma, daytrade_count, crypto_tier, alpaca_created_at, created_at, created_by, updated_at, updated_by
`

type UpsertAccountParams struct {
	Name                     string
	AccountNumber            *string
	AlpacaID                 *string
	Status                   *string
	CryptoStatus             *string
	Currency                 *string
	BuyingPower              pgtype.Numeric
	RegtBuyingPower          pgtype.Numeric
	DaytradingBuyingPower    pgtype.Numeric
	EffectiveBuyingPower     pgtype.Numeric
	NonMarginableBuyingPower pgtype.Numeric
	BodDtbp                  pgtype.Numeric
	Cash                     pgtype.Numeric
	AccruedFees              pgtype.Numeric
	PortfolioValue           pgtype.Numeric
	PatternDayTrader         *bool
	TradingBlocked           *bool
	TransfersBlocked         *bool
	AccountBlocked           *bool
	ShortingEnabled          *bool
	TradeSuspendedByUser     *bool
	Multiplier               pgtype.Numeric
	Equity                   pgtype.Numeric
	LastEquity               pgtype.Numeric
	LongMarketValue          pgtype.Numeric
	ShortMarketValue         pgtype.Numeric
	PositionMarketValue      pgtype.Numeric
	InitialMargin            pgtype.Numeric
	MaintenanceMargin        pgtype.Numeric
	LastMaintenanceMargin    pgtype.Numeric
	Sma                      pgtype.Numeric
	DaytradeCount            *int64
	CryptoTier               *int32
	AlpacaCreatedAt          pgtype.Timestamp
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, UpsertAccount,
		arg.Name,
		arg.AccountNumber,
		arg.AlpacaID,
		arg.Status,
		arg.CryptoStatus,
		arg.Currency,
		arg.BuyingPower,
		arg.RegtBuyingPower,
		arg.DaytradingBuyingPower,
		arg.EffectiveBuyingPower,
		arg.NonMarginableBuyingPower,
		arg.BodDtbp,
		arg.Cash,
		arg.AccruedFees,
		arg.PortfolioValue,
		arg.PatternDayTrader,
		arg.TradingBlocked,
		arg.TransfersBlocked,
		arg.AccountBlocked,
		arg.ShortingEnabled,
		arg.TradeSuspendedByUser,
		arg.Multiplier,
		arg.Equity,
		arg.LastEquity,
		arg.LongMarketValue,
		arg.ShortMarketValue,
		arg.PositionMarketValue,
		arg.InitialMargin,
		arg.MaintenanceMargin,
		arg.LastMaintenanceMargin,
		arg.Sma,
		arg.DaytradeCount,
		arg.CryptoTier,
		arg.AlpacaCreatedAt,
	)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountNumber,
		&i.AlpacaID,
		&i.Status,
		&i.CryptoStatus,
		&i.Currency,
		&i.BuyingPower,
		&i.RegtBuyingPower,
		&i.DaytradingBuyingPower,
		&i.EffectiveBuyingPower,
		&i.NonMarginableBuyingPower,
		&i.BodDtbp,
		&i.Cash,
		&i.AccruedFees,
		&i.PortfolioValue,
		&i.PatternDayTrader,
		&i.TradingBlocked,
		&i.TransfersBlocked,
		&i.AccountBlocked,
		&i.ShortingEnabled,
		&i.TradeSuspendedByUser,
		&i.Multiplier,
		&i.Equity,
		&i.LastEquity,
		&i.LongMarketValue,
		&i.ShortMarketValue,
		&i.PositionMarketValue,
		&i.InitialMargin,
		&i.MaintenanceMargin,
		&i.LastMaintenanceMargin,
		&i.Sma,
		&i.DaytradeCount,
		&i.CryptoTier,
		&i.AlpacaCreatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
