// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateActivity = `-- name: CreateActivity :one
INSERT INTO app.activity (
    account_id, activity_id, activity_type, transaction_time, type, price, qty,
    side, symbol, leaves_qty, cum_qty, date, net_amount, description,
    per_share_amount, order_id, order_status, status, is_option, options_income,
    symbol_derived, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, NOW(), 'system', NOW(), 'system'
)
RETURNING id, account_id, activity_id, activity_type, transaction_time, type, price, qty, side, symbol, leaves_qty, cum_qty, date, net_amount, description, per_share_amount, order_id, order_status, status, created_at, created_by, updated_at, updated_by, is_option, options_income, symbol_derived
`

type CreateActivityParams struct {
	AccountID       int32
	ActivityID      string
	ActivityType    string
	TransactionTime pgtype.Timestamp
	Type            *string
	Price           pgtype.Numeric
	Qty             pgtype.Numeric
	Side            *string
	Symbol          *string
	LeavesQty       pgtype.Numeric
	CumQty          pgtype.Numeric
	Date            pgtype.Date
	NetAmount       pgtype.Numeric
	Description     *string
	PerShareAmount  pgtype.Numeric
	OrderID         *string
	OrderStatus     *string
	Status          *string
	IsOption        *bool
	OptionsIncome   pgtype.Numeric
	SymbolDerived   *string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (AppActivity, error) {
	row := q.db.QueryRow(ctx, CreateActivity,
		arg.AccountID,
		arg.ActivityID,
		arg.ActivityType,
		arg.TransactionTime,
		arg.Type,
		arg.Price,
		arg.Qty,
		arg.Side,
		arg.Symbol,
		arg.LeavesQty,
		arg.CumQty,
		arg.Date,
		arg.NetAmount,
		arg.Description,
		arg.PerShareAmount,
		arg.OrderID,
		arg.OrderStatus,
		arg.Status,
		arg.IsOption,
		arg.OptionsIncome,
		arg.SymbolDerived,
	)
	var i AppActivity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ActivityID,
		&i.ActivityType,
		&i.TransactionTime,
		&i.Type,
		&i.Price,
		&i.Qty,
		&i.Side,
		&i.Symbol,
		&i.LeavesQty,
		&i.CumQty,
		&i.Date,
		&i.NetAmount,
		&i.Description,
		&i.PerShareAmount,
		&i.OrderID,
		&i.OrderStatus,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.IsOption,
		&i.OptionsIncome,
		&i.SymbolDerived,
	)
	return i, err
}

const GetActivityByAccountAndID = `-- name: GetActivityByAccountAndID :one
SELECT id, account_id, activity_id, activity_type, transaction_time, type, price, qty, side, symbol, leaves_qty, cum_qty, date, net_amount, description, per_share_amount, order_id, order_status, status, created_at, created_by, updated_at, updated_by, is_option, options_income, symbol_derived FROM app.activity
WHERE account_id = $1 AND activity_id = $2
`

type GetActivityByAccountAndIDParams struct {
	AccountID  int32
	ActivityID string
}

func (q *Queries) GetActivityByAccountAndID(ctx context.Context, arg GetActivityByAccountAndIDParams) (AppActivity, error) {
	row := q.db.QueryRow(ctx, GetActivityByAccountAndID, arg.AccountID, arg.ActivityID)
	var i AppActivity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ActivityID,
		&i.ActivityType,
		&i.TransactionTime,
		&i.Type,
		&i.Price,
		&i.Qty,
		&i.Side,
		&i.Symbol,
		&i.LeavesQty,
		&i.CumQty,
		&i.Date,
		&i.NetAmount,
		&i.Description,
		&i.PerShareAmount,
		&i.OrderID,
		&i.OrderStatus,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.IsOption,
		&i.OptionsIncome,
		&i.SymbolDerived,
	)
	return i, err
}

const GetLatestActivityByAccountID = `-- name: GetLatestActivityByAccountID :one
SELECT id, account_id, activity_id, activity_type, transaction_time, type, price, qty, side, symbol, leaves_qty, cum_qty, date, net_amount, description, per_share_amount, order_id, order_status, status, created_at, created_by, updated_at, updated_by, is_option, options_income, symbol_derived FROM app.activity
WHERE account_id = $1
ORDER BY transaction_time DESC
LIMIT 1
`

func (q *Queries) GetLatestActivityByAccountID(ctx context.Context, accountID int32) (AppActivity, error) {
	row := q.db.QueryRow(ctx, GetLatestActivityByAccountID, accountID)
	var i AppActivity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ActivityID,
		&i.ActivityType,
		&i.TransactionTime,
		&i.Type,
		&i.Price,
		&i.Qty,
		&i.Side,
		&i.Symbol,
		&i.LeavesQty,
		&i.CumQty,
		&i.Date,
		&i.NetAmount,
		&i.Description,
		&i.PerShareAmount,
		&i.OrderID,
		&i.OrderStatus,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.IsOption,
		&i.OptionsIncome,
		&i.SymbolDerived,
	)
	return i, err
}

const ListActivitiesByAccountID = `-- name: ListActivitiesByAccountID :many
SELECT id, account_id, activity_id, activity_type, transaction_time, type, price, qty, side, symbol, leaves_qty, cum_qty, date, net_amount, description, per_share_amount, order_id, order_status, status, created_at, created_by, updated_at, updated_by, is_option, options_income, symbol_derived FROM app.activity
WHERE account_id = $1
ORDER BY transaction_time DESC
LIMIT $2 OFFSET $3
`

type ListActivitiesByAccountIDParams struct {
	AccountID int32
	Limit     int32
	Offset    int32
}

func (q *Queries) ListActivitiesByAccountID(ctx context.Context, arg ListActivitiesByAccountIDParams) ([]AppActivity, error) {
	rows, err := q.db.Query(ctx, ListActivitiesByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppActivity{}
	for rows.Next() {
		var i AppActivity
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ActivityID,
			&i.ActivityType,
			&i.TransactionTime,
			&i.Type,
			&i.Price,
			&i.Qty,
			&i.Side,
			&i.Symbol,
			&i.LeavesQty,
			&i.CumQty,
			&i.Date,
			&i.NetAmount,
			&i.Description,
			&i.PerShareAmount,
			&i.OrderID,
			&i.OrderStatus,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.IsOption,
			&i.OptionsIncome,
			&i.SymbolDerived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
