// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corporate_action.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetCorporateActionByID = `-- name: GetCorporateActionByID :one
SELECT id, account_id, corporate_actions_id, ca_type, ca_sub_type, initiating_symbol, initiating_original_cusip, target_symbol, target_original_cusip, declaration_date, expiration_date, record_date, payable_date, cash, old_rate, new_rate, last_synced_at, created_at, created_by, updated_at, updated_by FROM app.corporate_action WHERE corporate_actions_id = $1
`

func (q *Queries) GetCorporateActionByID(ctx context.Context, corporateActionsID *string) (AppCorporateAction, error) {
	row := q.db.QueryRow(ctx, GetCorporateActionByID, corporateActionsID)
	var i AppCorporateAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CorporateActionsID,
		&i.CaType,
		&i.CaSubType,
		&i.InitiatingSymbol,
		&i.InitiatingOriginalCusip,
		&i.TargetSymbol,
		&i.TargetOriginalCusip,
		&i.DeclarationDate,
		&i.ExpirationDate,
		&i.RecordDate,
		&i.PayableDate,
		&i.Cash,
		&i.OldRate,
		&i.NewRate,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetLatestCorporateActionByAccountID = `-- name: GetLatestCorporateActionByAccountID :one
SELECT id, account_id, corporate_actions_id, ca_type, ca_sub_type, initiating_symbol, initiating_original_cusip, target_symbol, target_original_cusip, declaration_date, expiration_date, record_date, payable_date, cash, old_rate, new_rate, last_synced_at, created_at, created_by, updated_at, updated_by FROM app.corporate_action
WHERE account_id = $1
ORDER BY last_synced_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCorporateActionByAccountID(ctx context.Context, accountID int32) (AppCorporateAction, error) {
	row := q.db.QueryRow(ctx, GetLatestCorporateActionByAccountID, accountID)
	var i AppCorporateAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CorporateActionsID,
		&i.CaType,
		&i.CaSubType,
		&i.InitiatingSymbol,
		&i.InitiatingOriginalCusip,
		&i.TargetSymbol,
		&i.TargetOriginalCusip,
		&i.DeclarationDate,
		&i.ExpirationDate,
		&i.RecordDate,
		&i.PayableDate,
		&i.Cash,
		&i.OldRate,
		&i.NewRate,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListCorporateActionsByAccountID = `-- name: ListCorporateActionsByAccountID :many
SELECT id, account_id, corporate_actions_id, ca_type, ca_sub_type, initiating_symbol, initiating_original_cusip, target_symbol, target_original_cusip, declaration_date, expiration_date, record_date, payable_date, cash, old_rate, new_rate, last_synced_at, created_at, created_by, updated_at, updated_by FROM app.corporate_action
WHERE account_id = $1
ORDER BY last_synced_at DESC
LIMIT $2 OFFSET $3
`

type ListCorporateActionsByAccountIDParams struct {
	AccountID int32
	Limit     int32
	Offset    int32
}

func (q *Queries) ListCorporateActionsByAccountID(ctx context.Context, arg ListCorporateActionsByAccountIDParams) ([]AppCorporateAction, error) {
	rows, err := q.db.Query(ctx, ListCorporateActionsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCorporateAction{}
	for rows.Next() {
		var i AppCorporateAction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CorporateActionsID,
			&i.CaType,
			&i.CaSubType,
			&i.InitiatingSymbol,
			&i.InitiatingOriginalCusip,
			&i.TargetSymbol,
			&i.TargetOriginalCusip,
			&i.DeclarationDate,
			&i.ExpirationDate,
			&i.RecordDate,
			&i.PayableDate,
			&i.Cash,
			&i.OldRate,
			&i.NewRate,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertCorporateAction = `-- name: UpsertCorporateAction :one
INSERT INTO app.corporate_action (
    account_id, corporate_actions_id, ca_type, ca_sub_type, initiating_symbol,
    initiating_original_cusip, target_symbol, target_original_cusip,
    declaration_date, expiration_date, record_date, payable_date, cash, old_rate,
    new_rate, last_synced_at, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    NOW(), 'system', NOW(), 'system'
)
ON CONFLICT (corporate_actions_id) DO UPDATE SET
    ca_type = EXCLUDED.ca_type,
    ca_sub_type = EXCLUDED.ca_sub_type,
    initiating_symbol = EXCLUDED.initiating_symbol,
    initiating_original_cusip = EXCLUDED.initiating_original_cusip,
    target_symbol = EXCLUDED.target_symbol,
    target_original_cusip = EXCLUDED.target_original_cusip,
    declaration_date = EXCLUDED.declaration_date,
    expiration_date = EXCLUDED.expiration_date,
    record_date = EXCLUDED.record_date,
    payable_date = EXCLUDED.payable_date,
    cash = EXCLUDED.cash,
    old_rate = EXCLUDED.old_rate,
    new_rate = EXCLUDED.new_rate,
    last_synced_at = EXCLUDED.last_synced_at,
    updated_at = NOW(),
    updated_by = 'system'
RETURNING id, account_id, corporate_actions_id, ca_type, ca_sub_type, initiating_symbol, initiating_original_cusip, target_symbol, target_original_cusip, declaration_date, expiration_date, record_date, payable_date, cash, old_rate, new_rate, last_synced_at, created_at, created_by, updated_at, updated_by
`

type UpsertCorporateActionParams struct {
	AccountID               int32
	CorporateActionsID      *string
	CaType                  *string
	CaSubType               *string
	InitiatingSymbol        *string
	InitiatingOriginalCusip *string
	TargetSymbol            *string
	TargetOriginalCusip     *string
	DeclarationDate         *string
	ExpirationDate          *string
	RecordDate              *string
	PayableDate             *string
	Cash                    *string
	OldRate                 *string
	NewRate                 *string
	LastSyncedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertCorporateAction(ctx context.Context, arg UpsertCorporateActionParams) (AppCorporateAction, error) {
	row := q.db.QueryRow(ctx, UpsertCorporateAction,
		arg.AccountID,
		arg.CorporateActionsID,
		arg.CaType,
		arg.CaSubType,
		arg.InitiatingSymbol,
		arg.InitiatingOriginalCusip,
		arg.TargetSymbol,
		arg.TargetOriginalCusip,
		arg.DeclarationDate,
		arg.ExpirationDate,
		arg.RecordDate,
		arg.PayableDate,
		arg.Cash,
		arg.OldRate,
		arg.NewRate,
		arg.LastSyncedAt,
	)
	var i AppCorporateAction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CorporateActionsID,
		&i.CaType,
		&i.CaSubType,
		&i.InitiatingSymbol,
		&i.InitiatingOriginalCusip,
		&i.TargetSymbol,
		&i.TargetOriginalCusip,
		&i.DeclarationDate,
		&i.ExpirationDate,
		&i.RecordDate,
		&i.PayableDate,
		&i.Cash,
		&i.OldRate,
		&i.NewRate,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
