// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAccount struct {
	ID                       int32
	Name                     string
	AccountNumber            *string
	AlpacaID                 *string
	Status                   *string
	CryptoStatus             *string
	Currency                 *string
	BuyingPower              pgtype.Numeric
	RegtBuyingPower          pgtype.Numeric
	DaytradingBuyingPower    pgtype.Numeric
	EffectiveBuyingPower     pgtype.Numeric
	NonMarginableBuyingPower pgtype.Numeric
	BodDtbp                  pgtype.Numeric
	Cash                     pgtype.Numeric
	AccruedFees              pgtype.Numeric
	PortfolioValue           pgtype.Numeric
	PatternDayTrader         *bool
	TradingBlocked           *bool
	TransfersBlocked         *bool
	AccountBlocked           *bool
	ShortingEnabled          *bool
	TradeSuspendedByUser     *bool
	Multiplier               pgtype.Numeric
	Equity                   pgtype.Numeric
	LastEquity               pgtype.Numeric
	LongMarketValue          pgtype.Numeric
	ShortMarketValue         pgtype.Numeric
	PositionMarketValue      pgtype.Numeric
	InitialMargin            pgtype.Numeric
	MaintenanceMargin        pgtype.Numeric
	LastMaintenanceMargin    pgtype.Numeric
	Sma                      pgtype.Numeric
	DaytradeCount            *int64
	CryptoTier               *int32
	AlpacaCreatedAt          pgtype.Timestamp
	CreatedAt                pgtype.Timestamp
	CreatedBy                string
	UpdatedAt                pgtype.Timestamp
	UpdatedBy                string
}

type AppActivity struct {
	ID              int32
	AccountID       int32
	ActivityID      string
	ActivityType    string
	TransactionTime pgtype.Timestamp
	Type            *string
	Price           pgtype.Numeric
	Qty             pgtype.Numeric
	Side            *string
	Symbol          *string
	LeavesQty       pgtype.Numeric
	CumQty          pgtype.Numeric
	Date            pgtype.Date
	NetAmount       pgtype.Numeric
	Description     *string
	PerShareAmount  pgtype.Numeric
	OrderID         *string
	OrderStatus     *string
	Status          *string
	CreatedAt       pgtype.Timestamp
	CreatedBy       string
	UpdatedAt       pgtype.Timestamp
	UpdatedBy       string
	IsOption        *bool
	OptionsIncome   pgtype.Numeric
	SymbolDerived   *string
}

type AppCorporateAction struct {
	ID                      int32
	AccountID               int32
	CorporateActionsID      *string
	CaType                  *string
	CaSubType               *string
	InitiatingSymbol        *string
	InitiatingOriginalCusip *string
	TargetSymbol            *string
	TargetOriginalCusip     *string
	DeclarationDate         *string
	ExpirationDate          *string
	RecordDate              *string
	PayableDate             *string
	Cash                    *string
	OldRate                 *string
	NewRate                 *string
	LastSyncedAt            pgtype.Timestamptz
	CreatedAt               pgtype.Timestamp
	CreatedBy               string
	UpdatedAt               pgtype.Timestamp
	UpdatedBy               string
}

type AppOrder struct {
	ID              int32
	AccountID       int64
	ClientOrderID   string
	AssetID         *string
	Symbol          *string
	Side            *string
	Type            *string
	OrderClass      *string
	TimeInForce     *string
	Status          *string
	Quantity        pgtype.Numeric
	Notional        pgtype.Numeric
	FilledQty       pgtype.Numeric
	FilledAvgPrice  pgtype.Numeric
	LimitPrice      pgtype.Numeric
	StopPrice       pgtype.Numeric
	AlpacaCreatedAt pgtype.Timestamptz
	AlpacaUpdatedAt pgtype.Timestamptz
	SubmittedAt     pgtype.Timestamptz
	FilledAt        pgtype.Timestamptz
	ExpiredAt       pgtype.Timestamptz
	CanceledAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamp
	CreatedBy       string
	UpdatedAt       pgtype.Timestamp
	UpdatedBy       string
}

type AppPortfolio struct {
	ID           int32
	AccountID    int32
	PortfolioKey *string
	Name         string
	Weight       float64
	CreatedAt    pgtype.Timestamp
	CreatedBy    string
	UpdatedAt    pgtype.Timestamp
	UpdatedBy    string
}

type AppPortfolioSymbol struct {
	ID          int32
	PortfolioID int64
	Symbol      string
	Weight      float64
	CreatedAt   pgtype.Timestamp
	CreatedBy   string
	UpdatedAt   pgtype.Timestamp
	UpdatedBy   string
}

type AppPosition struct {
	ID            int32
	AccountID     int64
	Symbol        string
	Quantity      pgtype.Numeric
	AvgEntryPrice pgtype.Numeric
	MarketValue   pgtype.Numeric
	UnrealizedPl  pgtype.Numeric
	IsCurrent     *bool
	RecordedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamp
	CreatedBy     string
	UpdatedAt     pgtype.Timestamp
	UpdatedBy     string
}

type AppWatchlist struct {
	ID          int32
	AccountID   int32
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamp
	CreatedBy   string
	UpdatedAt   pgtype.Timestamp
	UpdatedBy   string
}

type AppWatchlistSymbol struct {
	ID          int32
	WatchlistID int32
	Symbol      string
	CreatedAt   pgtype.Timestamp
	CreatedBy   string
	UpdatedAt   pgtype.Timestamp
	UpdatedBy   string
}

type AppWithholding struct {
	ID          int32
	AccountID   int32
	Symbol      *string
	TaxType     *string
	Amount      pgtype.Numeric
	Currency    *string
	OccurredAt  pgtype.Timestamptz
	Description *string
	CreatedAt   pgtype.Timestamp
	CreatedBy   string
	UpdatedAt   pgtype.Timestamp
	UpdatedBy   string
}
