// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetLatestOrderByAccountID = `-- name: GetLatestOrderByAccountID :one
SELECT id, account_id, client_order_id, asset_id, symbol, side, type, order_class, time_in_force, status, quantity, notional, filled_qty, filled_avg_price, limit_price, stop_price, alpaca_created_at, alpaca_updated_at, submitted_at, filled_at, expired_at, canceled_at, created_at, created_by, updated_at, updated_by FROM app.order
WHERE account_id = $1
ORDER BY alpaca_created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOrderByAccountID(ctx context.Context, accountID int64) (AppOrder, error) {
	row := q.db.QueryRow(ctx, GetLatestOrderByAccountID, accountID)
	var i AppOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientOrderID,
		&i.AssetID,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.OrderClass,
		&i.TimeInForce,
		&i.Status,
		&i.Quantity,
		&i.Notional,
		&i.FilledQty,
		&i.FilledAvgPrice,
		&i.LimitPrice,
		&i.StopPrice,
		&i.AlpacaCreatedAt,
		&i.AlpacaUpdatedAt,
		&i.SubmittedAt,
		&i.FilledAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetOrderByClientOrderID = `-- name: GetOrderByClientOrderID :one
SELECT id, account_id, client_order_id, asset_id, symbol, side, type, order_class, time_in_force, status, quantity, notional, filled_qty, filled_avg_price, limit_price, stop_price, alpaca_created_at, alpaca_updated_at, submitted_at, filled_at, expired_at, canceled_at, created_at, created_by, updated_at, updated_by FROM app.order WHERE client_order_id = $1
`

func (q *Queries) GetOrderByClientOrderID(ctx context.Context, clientOrderID string) (AppOrder, error) {
	row := q.db.QueryRow(ctx, GetOrderByClientOrderID, clientOrderID)
	var i AppOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientOrderID,
		&i.AssetID,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.OrderClass,
		&i.TimeInForce,
		&i.Status,
		&i.Quantity,
		&i.Notional,
		&i.FilledQty,
		&i.FilledAvgPrice,
		&i.LimitPrice,
		&i.StopPrice,
		&i.AlpacaCreatedAt,
		&i.AlpacaUpdatedAt,
		&i.SubmittedAt,
		&i.FilledAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListOrdersByAccountID = `-- name: ListOrdersByAccountID :many
SELECT id, account_id, client_order_id, asset_id, symbol, side, type, order_class, time_in_force, status, quantity, notional, filled_qty, filled_avg_price, limit_price, stop_price, alpaca_created_at, alpaca_updated_at, submitted_at, filled_at, expired_at, canceled_at, created_at, created_by, updated_at, updated_by FROM app.order
WHERE account_id = $1
ORDER BY alpaca_created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByAccountIDParams struct {
	AccountID int64
	Limit     int32
	Offset    int32
}

func (q *Queries) ListOrdersByAccountID(ctx context.Context, arg ListOrdersByAccountIDParams) ([]AppOrder, error) {
	rows, err := q.db.Query(ctx, ListOrdersByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppOrder{}
	for rows.Next() {
		var i AppOrder
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientOrderID,
			&i.AssetID,
			&i.Symbol,
			&i.Side,
			&i.Type,
			&i.OrderClass,
			&i.TimeInForce,
			&i.Status,
			&i.Quantity,
			&i.Notional,
			&i.FilledQty,
			&i.FilledAvgPrice,
			&i.LimitPrice,
			&i.StopPrice,
			&i.AlpacaCreatedAt,
			&i.AlpacaUpdatedAt,
			&i.SubmittedAt,
			&i.FilledAt,
			&i.ExpiredAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertOrder = `-- name: UpsertOrder :one
INSERT INTO app.order (
    account_id, client_order_id, asset_id, symbol, side, type, order_class,
    time_in_force, status, quantity, notional, filled_qty, filled_avg_price,
    limit_price, stop_price, alpaca_created_at, alpaca_updated_at, submitted_at,
    filled_at, expired_at, canceled_at, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, NOW(), 'system', NOW(), 'system'
)
ON CONFLICT (client_order_id) DO UPDATE SET
    asset_id = EXCLUDED.asset_id,
    symbol = EXCLUDED.symbol,
    side = EXCLUDED.side,
    type = EXCLUDED.type,
    order_class = EXCLUDED.order_class,
    time_in_force = EXCLUDED.time_in_force,
    status = EXCLUDED.status,
    quantity = EXCLUDED.quantity,
    notional = EXCLUDED.notional,
    filled_qty = EXCLUDED.filled_qty,
    filled_avg_price = EXCLUDED.filled_avg_price,
    limit_price = EXCLUDED.limit_price,
    stop_price = EXCLUDED.stop_price,
    alpaca_created_at = EXCLUDED.alpaca_created_at,
    alpaca_updated_at = EXCLUDED.alpaca_updated_at,
    submitted_at = EXCLUDED.submitted_at,
    filled_at = EXCLUDED.filled_at,
    expired_at = EXCLUDED.expired_at,
    canceled_at = EXCLUDED.canceled_at,
    updated_at = NOW(),
    updated_by = 'system'
RETURNING id, account_id, client_order_id, asset_id, symbol, side, type, order_class, time_in_force, status, quantity, notional, filled_qty, filled_avg_price, limit_price, stop_price, alpaca_created_at, alpaca_updated_at, submitted_at, filled_at, expired_at, canceled_at, created_at, created_by, updated_at, updated_by
`

type UpsertOrderParams struct {
	AccountID       int64
	ClientOrderID   string
	AssetID         *string
	Symbol          *string
	Side            *string
	Type            *string
	OrderClass      *string
	TimeInForce     *string
	Status          *string
	Quantity        pgtype.Numeric
	Notional        pgtype.Numeric
	FilledQty       pgtype.Numeric
	FilledAvgPrice  pgtype.Numeric
	LimitPrice      pgtype.Numeric
	StopPrice       pgtype.Numeric
	AlpacaCreatedAt pgtype.Timestamptz
	AlpacaUpdatedAt pgtype.Timestamptz
	SubmittedAt     pgtype.Timestamptz
	FilledAt        pgtype.Timestamptz
	ExpiredAt       pgtype.Timestamptz
	CanceledAt      pgtype.Timestamptz
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) (AppOrder, error) {
	row := q.db.QueryRow(ctx, UpsertOrder,
		arg.AccountID,
		arg.ClientOrderID,
		arg.AssetID,
		arg.Symbol,
		arg.Side,
		arg.Type,
		arg.OrderClass,
		arg.TimeInForce,
		arg.Status,
		arg.Quantity,
		arg.Notional,
		arg.FilledQty,
		arg.FilledAvgPrice,
		arg.LimitPrice,
		arg.StopPrice,
		arg.AlpacaCreatedAt,
		arg.AlpacaUpdatedAt,
		arg.SubmittedAt,
		arg.FilledAt,
		arg.ExpiredAt,
		arg.CanceledAt,
	)
	var i AppOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientOrderID,
		&i.AssetID,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.OrderClass,
		&i.TimeInForce,
		&i.Status,
		&i.Quantity,
		&i.Notional,
		&i.FilledQty,
		&i.FilledAvgPrice,
		&i.LimitPrice,
		&i.StopPrice,
		&i.AlpacaCreatedAt,
		&i.AlpacaUpdatedAt,
		&i.SubmittedAt,
		&i.FilledAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
