// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio.sql

package sqlc

import (
	"context"
)

const CreatePortfolio = `-- name: CreatePortfolio :one
INSERT INTO app.portfolio (
    account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, NOW(), 'system', NOW(), 'system'
)
RETURNING id, account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by
`

type CreatePortfolioParams struct {
	AccountID    int32
	PortfolioKey *string
	Name         string
	Weight       float64
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (AppPortfolio, error) {
	row := q.db.QueryRow(ctx, CreatePortfolio,
		arg.AccountID,
		arg.PortfolioKey,
		arg.Name,
		arg.Weight,
	)
	var i AppPortfolio
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PortfolioKey,
		&i.Name,
		&i.Weight,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const CreatePortfolioSymbol = `-- name: CreatePortfolioSymbol :one
INSERT INTO app.portfolio_symbol (
    portfolio_id, symbol, weight, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, NOW(), 'system', NOW(), 'system'
)
RETURNING id, portfolio_id, symbol, weight, created_at, created_by, updated_at, updated_by
`

type CreatePortfolioSymbolParams struct {
	PortfolioID int64
	Symbol      string
	Weight      float64
}

func (q *Queries) CreatePortfolioSymbol(ctx context.Context, arg CreatePortfolioSymbolParams) (AppPortfolioSymbol, error) {
	row := q.db.QueryRow(ctx, CreatePortfolioSymbol, arg.PortfolioID, arg.Symbol, arg.Weight)
	var i AppPortfolioSymbol
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Weight,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const DeletePortfolio = `-- name: DeletePortfolio :exec
DELETE FROM app.portfolio WHERE id = $1
`

func (q *Queries) DeletePortfolio(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeletePortfolio, id)
	return err
}

const DeletePortfolioSymbol = `-- name: DeletePortfolioSymbol :exec
DELETE FROM app.portfolio_symbol WHERE portfolio_id = $1 AND symbol = $2
`

type DeletePortfolioSymbolParams struct {
	PortfolioID int64
	Symbol      string
}

func (q *Queries) DeletePortfolioSymbol(ctx context.Context, arg DeletePortfolioSymbolParams) error {
	_, err := q.db.Exec(ctx, DeletePortfolioSymbol, arg.PortfolioID, arg.Symbol)
	return err
}

const GetPortfolioByAccount = `-- name: GetPortfolioByAccount :many
SELECT id, account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by FROM app.portfolio WHERE account_id = $1
`

func (q *Queries) GetPortfolioByAccount(ctx context.Context, accountID int32) ([]AppPortfolio, error) {
	rows, err := q.db.Query(ctx, GetPortfolioByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPortfolio{}
	for rows.Next() {
		var i AppPortfolio
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PortfolioKey,
			&i.Name,
			&i.Weight,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPortfolioByAccountAndName = `-- name: GetPortfolioByAccountAndName :one
SELECT id, account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by FROM app.portfolio WHERE account_id = $1 AND name = $2
`

type GetPortfolioByAccountAndNameParams struct {
	AccountID int32
	Name      string
}

func (q *Queries) GetPortfolioByAccountAndName(ctx context.Context, arg GetPortfolioByAccountAndNameParams) (AppPortfolio, error) {
	row := q.db.QueryRow(ctx, GetPortfolioByAccountAndName, arg.AccountID, arg.Name)
	var i AppPortfolio
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PortfolioKey,
		&i.Name,
		&i.Weight,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetPortfolioByID = `-- name: GetPortfolioByID :one
SELECT id, account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by FROM app.portfolio WHERE id = $1
`

func (q *Queries) GetPortfolioByID(ctx context.Context, id int32) (AppPortfolio, error) {
	row := q.db.QueryRow(ctx, GetPortfolioByID, id)
	var i AppPortfolio
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PortfolioKey,
		&i.Name,
		&i.Weight,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListPortfolioSymbolsByAccountID = `-- name: ListPortfolioSymbolsByAccountID :many
SELECT
    portfolio_symbol.symbol
FROM app.portfolio_symbol
    JOIN app.portfolio ON portfolio.id = portfolio_symbol.portfolio_id
WHERE portfolio.account_id = $1
ORDER BY symbol ASC
`

func (q *Queries) ListPortfolioSymbolsByAccountID(ctx context.Context, accountID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, ListPortfolioSymbolsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPortfoliosByAccountID = `-- name: ListPortfoliosByAccountID :many
SELECT id, account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by FROM app.portfolio WHERE account_id = $1 ORDER BY name ASC
`

func (q *Queries) ListPortfoliosByAccountID(ctx context.Context, accountID int32) ([]AppPortfolio, error) {
	rows, err := q.db.Query(ctx, ListPortfoliosByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPortfolio{}
	for rows.Next() {
		var i AppPortfolio
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PortfolioKey,
			&i.Name,
			&i.Weight,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePortfolio = `-- name: UpdatePortfolio :one
UPDATE app.portfolio
SET
    portfolio_key = $2,
    name = $3,
    weight = $4,
    updated_at = NOW(),
    updated_by = 'system'
WHERE id = $1
RETURNING id, account_id, portfolio_key, name, weight, created_at, created_by, updated_at, updated_by
`

type UpdatePortfolioParams struct {
	ID           int32
	PortfolioKey *string
	Name         string
	Weight       float64
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (AppPortfolio, error) {
	row := q.db.QueryRow(ctx, UpdatePortfolio,
		arg.ID,
		arg.PortfolioKey,
		arg.Name,
		arg.Weight,
	)
	var i AppPortfolio
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PortfolioKey,
		&i.Name,
		&i.Weight,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
