// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetPositionByAccountAndSymbol = `-- name: GetPositionByAccountAndSymbol :one
SELECT id, account_id, symbol, quantity, avg_entry_price, market_value, unrealized_pl, is_current, recorded_at, created_at, created_by, updated_at, updated_by FROM app.position WHERE account_id = $1 AND symbol = $2
`

type GetPositionByAccountAndSymbolParams struct {
	AccountID int64
	Symbol    string
}

func (q *Queries) GetPositionByAccountAndSymbol(ctx context.Context, arg GetPositionByAccountAndSymbolParams) (AppPosition, error) {
	row := q.db.QueryRow(ctx, GetPositionByAccountAndSymbol, arg.AccountID, arg.Symbol)
	var i AppPosition
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgEntryPrice,
		&i.MarketValue,
		&i.UnrealizedPl,
		&i.IsCurrent,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListCurrentPositionsByAccountID = `-- name: ListCurrentPositionsByAccountID :many
SELECT id, account_id, symbol, quantity, avg_entry_price, market_value, unrealized_pl, is_current, recorded_at, created_at, created_by, updated_at, updated_by FROM app.position
WHERE account_id = $1 AND is_current = TRUE
ORDER BY symbol ASC
`

func (q *Queries) ListCurrentPositionsByAccountID(ctx context.Context, accountID int64) ([]AppPosition, error) {
	rows, err := q.db.Query(ctx, ListCurrentPositionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPosition{}
	for rows.Next() {
		var i AppPosition
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Quantity,
			&i.AvgEntryPrice,
			&i.MarketValue,
			&i.UnrealizedPl,
			&i.IsCurrent,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPositionsByAccountID = `-- name: ListPositionsByAccountID :many
SELECT id, account_id, symbol, quantity, avg_entry_price, market_value, unrealized_pl, is_current, recorded_at, created_at, created_by, updated_at, updated_by FROM app.position
WHERE account_id = $1
ORDER BY symbol ASC
`

func (q *Queries) ListPositionsByAccountID(ctx context.Context, accountID int64) ([]AppPosition, error) {
	rows, err := q.db.Query(ctx, ListPositionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPosition{}
	for rows.Next() {
		var i AppPosition
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Quantity,
			&i.AvgEntryPrice,
			&i.MarketValue,
			&i.UnrealizedPl,
			&i.IsCurrent,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkPositionsStale = `-- name: MarkPositionsStale :exec
UPDATE app.position
SET is_current = FALSE, updated_at = NOW(), updated_by = 'system'
WHERE account_id = $1 AND is_current = TRUE
`

func (q *Queries) MarkPositionsStale(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, MarkPositionsStale, accountID)
	return err
}

const UpsertPosition = `-- name: UpsertPosition :one
INSERT INTO app.position (
    account_id, symbol, quantity, avg_entry_price, market_value, unrealized_pl,
    is_current, recorded_at, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), 'system', NOW(), 'system'
)
ON CONFLICT (account_id, symbol) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    avg_entry_price = EXCLUDED.avg_entry_price,
    market_value = EXCLUDED.market_value,
    unrealized_pl = EXCLUDED.unrealized_pl,
    is_current = EXCLUDED.is_current,
    recorded_at = EXCLUDED.recorded_at,
    updated_at = NOW(),
    updated_by = 'system'
RETURNING id, account_id, symbol, quantity, avg_entry_price, market_value, unrealized_pl, is_current, recorded_at, created_at, created_by, updated_at, updated_by
`

type UpsertPositionParams struct {
	AccountID     int64
	Symbol        string
	Quantity      pgtype.Numeric
	AvgEntryPrice pgtype.Numeric
	MarketValue   pgtype.Numeric
	UnrealizedPl  pgtype.Numeric
	IsCurrent     *bool
	RecordedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (AppPosition, error) {
	row := q.db.QueryRow(ctx, UpsertPosition,
		arg.AccountID,
		arg.Symbol,
		arg.Quantity,
		arg.AvgEntryPrice,
		arg.MarketValue,
		arg.UnrealizedPl,
		arg.IsCurrent,
		arg.RecordedAt,
	)
	var i AppPosition
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgEntryPrice,
		&i.MarketValue,
		&i.UnrealizedPl,
		&i.IsCurrent,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
