// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (AppActivity, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (AppPortfolio, error)
	CreatePortfolioSymbol(ctx context.Context, arg CreatePortfolioSymbolParams) (AppPortfolioSymbol, error)
	CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (AppWatchlist, error)
	CreateWatchlistSymbol(ctx context.Context, arg CreateWatchlistSymbolParams) (AppWatchlistSymbol, error)
	CreateWithholding(ctx context.Context, arg CreateWithholdingParams) (AppWithholding, error)
	DeletePortfolio(ctx context.Context, id int32) error
	DeletePortfolioSymbol(ctx context.Context, arg DeletePortfolioSymbolParams) error
	DeleteWatchlist(ctx context.Context, id int32) error
	DeleteWatchlistSymbol(ctx context.Context, arg DeleteWatchlistSymbolParams) error
	GetAccountByAlpacaID(ctx context.Context, alpacaID *string) (AppAccount, error)
	GetAccountByID(ctx context.Context, id int32) (AppAccount, error)
	GetAccountByNumber(ctx context.Context, accountNumber *string) (AppAccount, error)
	GetActivityByAccountAndID(ctx context.Context, arg GetActivityByAccountAndIDParams) (AppActivity, error)
	GetCorporateActionByID(ctx context.Context, corporateActionsID *string) (AppCorporateAction, error)
	GetLatestActivityByAccountID(ctx context.Context, accountID int32) (AppActivity, error)
	GetLatestCorporateActionByAccountID(ctx context.Context, accountID int32) (AppCorporateAction, error)
	GetLatestOrderByAccountID(ctx context.Context, accountID int64) (AppOrder, error)
	GetOrderByClientOrderID(ctx context.Context, clientOrderID string) (AppOrder, error)
	GetPortfolioByAccount(ctx context.Context, accountID int32) ([]AppPortfolio, error)
	GetPortfolioByAccountAndName(ctx context.Context, arg GetPortfolioByAccountAndNameParams) (AppPortfolio, error)
	GetPortfolioByID(ctx context.Context, id int32) (AppPortfolio, error)
	GetPositionByAccountAndSymbol(ctx context.Context, arg GetPositionByAccountAndSymbolParams) (AppPosition, error)
	GetWatchlistByAccountAndName(ctx context.Context, arg GetWatchlistByAccountAndNameParams) (AppWatchlist, error)
	GetWatchlistByID(ctx context.Context, id int32) (AppWatchlist, error)
	GetWithholdingByID(ctx context.Context, id int32) (AppWithholding, error)
	ListAccounts(ctx context.Context) ([]AppAccount, error)
	ListActivitiesByAccountID(ctx context.Context, arg ListActivitiesByAccountIDParams) ([]AppActivity, error)
	ListCorporateActionsByAccountID(ctx context.Context, arg ListCorporateActionsByAccountIDParams) ([]AppCorporateAction, error)
	ListCurrentPositionsByAccountID(ctx context.Context, accountID int64) ([]AppPosition, error)
	ListOrdersByAccountID(ctx context.Context, arg ListOrdersByAccountIDParams) ([]AppOrder, error)
	ListPortfolioSymbolsByAccountID(ctx context.Context, accountID int32) ([]string, error)
	ListPortfoliosByAccountID(ctx context.Context, accountID int32) ([]AppPortfolio, error)
	ListPositionsByAccountID(ctx context.Context, accountID int64) ([]AppPosition, error)
	ListWatchlistSymbolsByWatchlistID(ctx context.Context, watchlistID int32) ([]AppWatchlistSymbol, error)
	ListWatchlistsByAccountID(ctx context.Context, accountID int32) ([]AppWatchlist, error)
	ListWithholdingsByAccountID(ctx context.Context, arg ListWithholdingsByAccountIDParams) ([]AppWithholding, error)
	MarkPositionsStale(ctx context.Context, accountID int64) error
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (AppPortfolio, error)
	UpdateWatchlist(ctx context.Context, arg UpdateWatchlistParams) (AppWatchlist, error)
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) (AppAccount, error)
	UpsertCorporateAction(ctx context.Context, arg UpsertCorporateActionParams) (AppCorporateAction, error)
	UpsertOrder(ctx context.Context, arg UpsertOrderParams) (AppOrder, error)
	UpsertPosition(ctx context.Context, arg UpsertPositionParams) (AppPosition, error)
}

var _ Querier = (*Queries)(nil)
