// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package sqlc

import (
	"context"
)

const CreateWatchlist = `-- name: CreateWatchlist :one
INSERT INTO app.watchlist (
    account_id, name, description, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, NOW(), 'system', NOW(), 'system'
)
RETURNING id, account_id, name, description, created_at, created_by, updated_at, updated_by
`

type CreateWatchlistParams struct {
	AccountID   int32
	Name        string
	Description *string
}

func (q *Queries) CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (AppWatchlist, error) {
	row := q.db.QueryRow(ctx, CreateWatchlist, arg.AccountID, arg.Name, arg.Description)
	var i AppWatchlist
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const CreateWatchlistSymbol = `-- name: CreateWatchlistSymbol :one
INSERT INTO app.watchlist_symbol (
    watchlist_id, symbol, created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, NOW(), 'system', NOW(), 'system'
)
RETURNING id, watchlist_id, symbol, created_at, created_by, updated_at, updated_by
`

type CreateWatchlistSymbolParams struct {
	WatchlistID int32
	Symbol      string
}

func (q *Queries) CreateWatchlistSymbol(ctx context.Context, arg CreateWatchlistSymbolParams) (AppWatchlistSymbol, error) {
	row := q.db.QueryRow(ctx, CreateWatchlistSymbol, arg.WatchlistID, arg.Symbol)
	var i AppWatchlistSymbol
	err := row.Scan(
		&i.ID,
		&i.WatchlistID,
		&i.Symbol,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const DeleteWatchlist = `-- name: DeleteWatchlist :exec
DELETE FROM app.watchlist WHERE id = $1
`

func (q *Queries) DeleteWatchlist(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteWatchlist, id)
	return err
}

const DeleteWatchlistSymbol = `-- name: DeleteWatchlistSymbol :exec
DELETE FROM app.watchlist_symbol WHERE watchlist_id = $1 AND symbol = $2
`

type DeleteWatchlistSymbolParams struct {
	WatchlistID int32
	Symbol      string
}

func (q *Queries) DeleteWatchlistSymbol(ctx context.Context, arg DeleteWatchlistSymbolParams) error {
	_, err := q.db.Exec(ctx, DeleteWatchlistSymbol, arg.WatchlistID, arg.Symbol)
	return err
}

const GetWatchlistByAccountAndName = `-- name: GetWatchlistByAccountAndName :one
SELECT id, account_id, name, description, created_at, created_by, updated_at, updated_by FROM app.watchlist WHERE account_id = $1 AND name = $2
`

type GetWatchlistByAccountAndNameParams struct {
	AccountID int32
	Name      string
}

func (q *Queries) GetWatchlistByAccountAndName(ctx context.Context, arg GetWatchlistByAccountAndNameParams) (AppWatchlist, error) {
	row := q.db.QueryRow(ctx, GetWatchlistByAccountAndName, arg.AccountID, arg.Name)
	var i AppWatchlist
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetWatchlistByID = `-- name: GetWatchlistByID :one
SELECT id, account_id, name, description, created_at, created_by, updated_at, updated_by FROM app.watchlist WHERE id = $1
`

func (q *Queries) GetWatchlistByID(ctx context.Context, id int32) (AppWatchlist, error) {
	row := q.db.QueryRow(ctx, GetWatchlistByID, id)
	var i AppWatchlist
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListWatchlistSymbolsByWatchlistID = `-- name: ListWatchlistSymbolsByWatchlistID :many
SELECT id, watchlist_id, symbol, created_at, created_by, updated_at, updated_by FROM app.watchlist_symbol WHERE watchlist_id = $1 ORDER BY symbol ASC
`

func (q *Queries) ListWatchlistSymbolsByWatchlistID(ctx context.Context, watchlistID int32) ([]AppWatchlistSymbol, error) {
	rows, err := q.db.Query(ctx, ListWatchlistSymbolsByWatchlistID, watchlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppWatchlistSymbol{}
	for rows.Next() {
		var i AppWatchlistSymbol
		if err := rows.Scan(
			&i.ID,
			&i.WatchlistID,
			&i.Symbol,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWatchlistsByAccountID = `-- name: ListWatchlistsByAccountID :many
SELECT id, account_id, name, description, created_at, created_by, updated_at, updated_by FROM app.watchlist WHERE account_id = $1 ORDER BY name ASC
`

func (q *Queries) ListWatchlistsByAccountID(ctx context.Context, accountID int32) ([]AppWatchlist, error) {
	rows, err := q.db.Query(ctx, ListWatchlistsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppWatchlist{}
	for rows.Next() {
		var i AppWatchlist
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateWatchlist = `-- name: UpdateWatchlist :one
UPDATE app.watchlist
SET
    name = $2,
    description = $3,
    updated_at = NOW(),
    updated_by = 'system'
WHERE id = $1
RETURNING id, account_id, name, description, created_at, created_by, updated_at, updated_by
`

type UpdateWatchlistParams struct {
	ID          int32
	Name        string
	Description *string
}

func (q *Queries) UpdateWatchlist(ctx context.Context, arg UpdateWatchlistParams) (AppWatchlist, error) {
	row := q.db.QueryRow(ctx, UpdateWatchlist, arg.ID, arg.Name, arg.Description)
	var i AppWatchlist
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
