// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withholding.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateWithholding = `-- name: CreateWithholding :one
INSERT INTO app.withholding (
    account_id, symbol, tax_type, amount, currency, occurred_at, description,
    created_at, created_by, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), 'system', NOW(), 'system'
)
RETURNING id, account_id, symbol, tax_type, amount, currency, occurred_at, description, created_at, created_by, updated_at, updated_by
`

type CreateWithholdingParams struct {
	AccountID   int32
	Symbol      *string
	TaxType     *string
	Amount      pgtype.Numeric
	Currency    *string
	OccurredAt  pgtype.Timestamptz
	Description *string
}

func (q *Queries) CreateWithholding(ctx context.Context, arg CreateWithholdingParams) (AppWithholding, error) {
	row := q.db.QueryRow(ctx, CreateWithholding,
		arg.AccountID,
		arg.Symbol,
		arg.TaxType,
		arg.Amount,
		arg.Currency,
		arg.OccurredAt,
		arg.Description,
	)
	var i AppWithholding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.TaxType,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const GetWithholdingByID = `-- name: GetWithholdingByID :one
SELECT id, account_id, symbol, tax_type, amount, currency, occurred_at, description, created_at, created_by, updated_at, updated_by FROM app.withholding WHERE id = $1
`

func (q *Queries) GetWithholdingByID(ctx context.Context, id int32) (AppWithholding, error) {
	row := q.db.QueryRow(ctx, GetWithholdingByID, id)
	var i AppWithholding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.TaxType,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListWithholdingsByAccountID = `-- name: ListWithholdingsByAccountID :many
SELECT id, account_id, symbol, tax_type, amount, currency, occurred_at, description, created_at, created_by, updated_at, updated_by FROM app.withholding
WHERE account_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListWithholdingsByAccountIDParams struct {
	AccountID int32
	Limit     int32
	Offset    int32
}

func (q *Queries) ListWithholdingsByAccountID(ctx context.Context, arg ListWithholdingsByAccountIDParams) ([]AppWithholding, error) {
	rows, err := q.db.Query(ctx, ListWithholdingsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppWithholding{}
	for rows.Next() {
		var i AppWithholding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.TaxType,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
